import React from "react"
import { Button } from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/s3lzR0T5oGJIrhWcU7yb1H/%5BLAB%5D-Code-Connect-Demo-?node-id=9215%3A9074",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      variant: figma.enum("Variant", {
        Primary: "primary",
        Secondary: "secondary",
        Inverse: "inverse",
      }),
      iconEnd: figma.instance("↳ Icon End Instance"),
      iconStart: figma.instance("↳ Icon Start Instance"),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      label: figma.string("label"),
      state: figma.enum("State", {
        Active: "Active",
        Default: "Default",
        Disabled: "Disabled",
        Focus: "Focus",
        Hover: "Hover",
      }),
      // No matching props could be found for these Figma properties:
      // "iconEndInstance": figma.instance('↳ Icon End Instance'),
      // "iconStartInstance": figma.instance('↳ Icon Start Instance'),
      // "label": figma.string('Label'),
      // "iconEnd": figma.boolean('Icon End'),
      // "iconStart": figma.boolean('Icon Start')
    },
    example: (props) => (
      <Button
        disabled={props.disabled}
        variant={props.variant}
        state={props.state}
        size={props.size}
        iconEnd={props.iconEnd}
        iconStart={props.iconStart}
        
        label={props.label}
      />
    ),
  },
)
figma.connect(
  Button,
  "https://www.figma.com/design/s3lzR0T5oGJIrhWcU7yb1H/%5BLAB%5D-Code-Connect-Demo?node-id=15110-299&m=dev",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      icon: figma.instance("icon symbol"),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      label: figma.string("label"),
      state: figma.enum("State", {
        Active: "Active",
        Default: "Default",
        Disabled: "Disabled",
        Focus: "Focus",
        Hover: "Hover",
      }),
      // No matching props could be found for these Figma properties:
      // "iconEndInstance": figma.instance('↳ Icon End Instance'),
      // "iconStartInstance": figma.instance('↳ Icon Start Instance'),
      // "label": figma.string('Label'),
      // "iconEnd": figma.boolean('Icon End'),
      // "iconStart": figma.boolean('Icon Start')
    },
    example: (props) => (
      <Button
        disabled={props.disabled}
        state={props.state}
        size={props.size}
        icon={props.icon}
      >{props.label}</Button>
    ),
  },
)
